name: JS Actions

on:
  issues:
    types: [labeled]

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Composer Dependencies
        working-directory: ./app
        run: "npm i"
      - name: ha-ha
        uses: ./.github/actions/joke-action
